import torch.nn as nn
import torch.nn.functional as F

class DeconvNet(nn.Module):
    def __init__(self):
        super(DeconvNet, self).__init__()
        self.conv1_1 = nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, stride=1, padding=1)
        self.conv1_2 = nn.Conv2d(in_channels=64, out_channels=64, kernel_size=3, stride=1, padding=1)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0, return_indices=True)
        self.conv2_1 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding=1)
        self.conv2_2 = nn.Conv2d(in_channels=128, out_channels=128, kernel_size=3, stride=1, padding=1)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0, return_indices=True)
        self.conv3_1 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.conv3_2 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.conv3_3 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0, return_indices=True)
        self.conv4_1 = nn.Conv2d(in_channels=256, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.conv4_2 = nn.Conv2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.conv4_3 = nn.Conv2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.pool4 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0, return_indices=True)
        self.conv5_1 = nn.Conv2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.conv5_2 = nn.Conv2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.conv5_3 = nn.Conv2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.pool5 = nn.MaxPool2d(kernel_size=2, stride=2, padding=0, return_indices=True)
        self.fc6 = nn.Conv2d(in_channels=512, out_channels=4096, kernel_size=7, stride=1, padding=0)
        self.fc7 = nn.Conv2d(in_channels=4096, out_channels=4096, kernel_size=2, stride=1, padding=0)
        self.deconv_fc6 = nn.ConvTranspose2d(in_channels=4096, out_channels=512, kernel_size=7, stride=1, padding=0)
        self.unpool5 = nn.MaxUnpool2d(kernel_size=2, stride=2, padding=0)
        self.deconv5_1 = nn.ConvTranspose2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.deconv5_2 = nn.ConvTranspose2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.deconv5_3 = nn.ConvTranspose2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.unpool4 = nn.MaxUnpool2d(kernel_size=2, stride=2, padding=0)
        self.deconv4_1 = nn.ConvTranspose2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.deconv4_2 = nn.ConvTranspose2d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.deconv4_3 = nn.ConvTranspose2d(in_channels=512, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.unpool3 = nn.MaxUnpool2d(kernel_size=2, stride=2, padding=0)
        self.deconv3_1 = nn.ConvTranspose2d(in_channels=256, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.deconv3_2 = nn.ConvTranspose2d(in_channels=256, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.deconv3_3 = nn.ConvTranspose2d(in_channels=256, out_channels=128, kernel_size=3, stride=1, padding=1)
        self.unpool2 = nn.MaxUnpool2d(kernel_size=2, stride=2, padding=0)
        self.deconv2_1 = nn.ConvTranspose2d(in_channels=128, out_channels=128, kernel_size=3, stride=1, padding=1)
        self.deconv2_2 = nn.ConvTranspose2d(in_channels=128, out_channels=64, kernel_size=3, stride=1, padding=1)
        self.unpool1 = nn.MaxUnpool2d(kernel_size=2, stride=2, padding=0)
        self.deconv1_1 = nn.ConvTranspose2d(in_channels=64, out_channels=64, kernel_size=3, stride=1, padding=1)
        self.deconv1_2 = nn.ConvTranspose2d(in_channels=64, out_channels=21, kernel_size=3, stride=1, padding=1) #outchannels is number of classes
    
    def forward(self, x):
        x = F.relu(input=self.conv1_1(x))
        x = F.relu(input=self.conv1_2(x))
        x, indices1 = self.pool1(input=x)
        x = F.relu(input=self.conv2_1(x))
        x = F.relu(input=self.conv2_2(x))
        x, indices2 = self.pool2(input=x)
        x = F.relu(input=self.conv3_1(x))
        x = F.relu(input=self.conv3_2(x))
        x = F.relu(input=self.conv3_3(x))
        x, indices3 = self.pool3(input=x)
        x = F.relu(input=self.conv4_1(x))
        x = F.relu(input=self.conv4_2(x))
        x = F.relu(input=self.conv4_3(x))
        x, indices4 = self.pool4(input=x)
        x = F.relu(input=self.conv5_1(x))
        x = F.relu(input=self.conv5_2(x))
        x = F.relu(input=self.conv5_3(x))
        x, indices5 = self.pool5(input=x)
        x = F.relu(input=self.fc6(x))
        x = F.relu(input=self.fc7(x))
        x = F.relu(input=self.deconv_fc6(x))
        x = self.unpool5(input=x, indices=indices5)
        x = F.relu(input=self.deconv5_1(x))
        x = F.relu(input=self.deconv5_2(x))
        x = F.relu(input=self.deconv5_3(x))
        x = self.unpool4(input=x, indices=indices4)
        x = F.relu(input=self.deconv4_1(x))
        x = F.relu(input=self.deconv4_2(x))
        x = F.relu(input=self.deconv4_3(x))
        x = self.unpool3(input=x, indices=indices3)
        x = F.relu(input=self.deconv3_1(x))
        x = F.relu(input=self.deconv3_2(x))
        x = F.relu(input=self.deconv3_3(x))
        x = self.unpool2(input=x, indices=indices2)
        x = F.relu(input=self.deconv2_1(x))
        x = F.relu(input=self.deconv2_2(x))
        x = self.unpool1(input=x, indices=indices1)
        x = F.relu(input=self.deconv1_1(x))
        x = F.relu(input=self.deconv1_2(x))
        return x